// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator.proto

package calculator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	N1                   float64  `protobuf:"fixed64,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2                   float64  `protobuf:"fixed64,2,opt,name=n2,proto3" json:"n2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetN1() float64 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *AddRequest) GetN2() float64 {
	if m != nil {
		return m.N2
	}
	return 0
}

type SubtractRequest struct {
	N1                   float64  `protobuf:"fixed64,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2                   float64  `protobuf:"fixed64,2,opt,name=n2,proto3" json:"n2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubtractRequest) Reset()         { *m = SubtractRequest{} }
func (m *SubtractRequest) String() string { return proto.CompactTextString(m) }
func (*SubtractRequest) ProtoMessage()    {}
func (*SubtractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{1}
}

func (m *SubtractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubtractRequest.Unmarshal(m, b)
}
func (m *SubtractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubtractRequest.Marshal(b, m, deterministic)
}
func (m *SubtractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubtractRequest.Merge(m, src)
}
func (m *SubtractRequest) XXX_Size() int {
	return xxx_messageInfo_SubtractRequest.Size(m)
}
func (m *SubtractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubtractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubtractRequest proto.InternalMessageInfo

func (m *SubtractRequest) GetN1() float64 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *SubtractRequest) GetN2() float64 {
	if m != nil {
		return m.N2
	}
	return 0
}

type MultiplyRequest struct {
	N1                   float64  `protobuf:"fixed64,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2                   float64  `protobuf:"fixed64,2,opt,name=n2,proto3" json:"n2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplyRequest) Reset()         { *m = MultiplyRequest{} }
func (m *MultiplyRequest) String() string { return proto.CompactTextString(m) }
func (*MultiplyRequest) ProtoMessage()    {}
func (*MultiplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{2}
}

func (m *MultiplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyRequest.Unmarshal(m, b)
}
func (m *MultiplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyRequest.Marshal(b, m, deterministic)
}
func (m *MultiplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyRequest.Merge(m, src)
}
func (m *MultiplyRequest) XXX_Size() int {
	return xxx_messageInfo_MultiplyRequest.Size(m)
}
func (m *MultiplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyRequest proto.InternalMessageInfo

func (m *MultiplyRequest) GetN1() float64 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *MultiplyRequest) GetN2() float64 {
	if m != nil {
		return m.N2
	}
	return 0
}

type DivideRequest struct {
	N1                   float64  `protobuf:"fixed64,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2                   float64  `protobuf:"fixed64,2,opt,name=n2,proto3" json:"n2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivideRequest) Reset()         { *m = DivideRequest{} }
func (m *DivideRequest) String() string { return proto.CompactTextString(m) }
func (*DivideRequest) ProtoMessage()    {}
func (*DivideRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{3}
}

func (m *DivideRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivideRequest.Unmarshal(m, b)
}
func (m *DivideRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivideRequest.Marshal(b, m, deterministic)
}
func (m *DivideRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivideRequest.Merge(m, src)
}
func (m *DivideRequest) XXX_Size() int {
	return xxx_messageInfo_DivideRequest.Size(m)
}
func (m *DivideRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DivideRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DivideRequest proto.InternalMessageInfo

func (m *DivideRequest) GetN1() float64 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *DivideRequest) GetN2() float64 {
	if m != nil {
		return m.N2
	}
	return 0
}

type Response struct {
	Response             float64  `protobuf:"fixed64,1,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() float64 {
	if m != nil {
		return m.Response
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "calculator.AddRequest")
	proto.RegisterType((*SubtractRequest)(nil), "calculator.SubtractRequest")
	proto.RegisterType((*MultiplyRequest)(nil), "calculator.MultiplyRequest")
	proto.RegisterType((*DivideRequest)(nil), "calculator.DivideRequest")
	proto.RegisterType((*Response)(nil), "calculator.Response")
}

func init() {
	proto.RegisterFile("calculator.proto", fileDescriptor_c686ea360062a8cf)
}

var fileDescriptor_c686ea360062a8cf = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xe9, 0x70, 0x71, 0x39, 0xa6, 0xa4, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1,
	0x71, 0x31, 0xe5, 0x19, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x06, 0x31, 0xe5, 0x19, 0x82, 0xf9,
	0x46, 0x12, 0x4c, 0x50, 0xbe, 0x91, 0x92, 0x21, 0x17, 0x7f, 0x70, 0x69, 0x52, 0x49, 0x51, 0x62,
	0x72, 0x09, 0x09, 0x5a, 0x7c, 0x4b, 0x73, 0x4a, 0x32, 0x0b, 0x72, 0x2a, 0x89, 0xd5, 0xa2, 0xcf,
	0xc5, 0xeb, 0x92, 0x59, 0x96, 0x99, 0x92, 0x4a, 0xac, 0x06, 0x35, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x29, 0x04, 0x1b, 0xaa, 0x03, 0xce, 0x37, 0xfa, 0xc5, 0xc8,
	0xc5, 0xe5, 0x0c, 0xf7, 0xbb, 0x90, 0x31, 0x17, 0xb3, 0x63, 0x4a, 0x8a, 0x90, 0x98, 0x1e, 0x52,
	0x08, 0x21, 0x02, 0x43, 0x4a, 0x04, 0x59, 0x1c, 0x6e, 0xbe, 0x2d, 0x17, 0x07, 0x2c, 0x08, 0x84,
	0xa4, 0x91, 0x55, 0xa0, 0x05, 0x0c, 0x6e, 0xed, 0xb0, 0xe0, 0x40, 0xd5, 0x8e, 0x16, 0x48, 0x38,
	0xb4, 0x5b, 0x72, 0xb1, 0x41, 0x82, 0x46, 0x48, 0x12, 0x59, 0x1e, 0x25, 0xb8, 0xb0, 0x6b, 0x75,
	0xe2, 0x8d, 0xe2, 0xd6, 0x47, 0x88, 0x27, 0xb1, 0x81, 0xd3, 0x82, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xa4, 0xfe, 0xe0, 0x1f, 0x02, 0x00, 0x00,
}
